/*
Write a MongoDB aggregation query to calculate the total revenue generated by 
the hospital on a month-by-month basis.


Sample output:
--------------
[ 
    { totalRevenue: 1000, month: 3 }, 
    { totalRevenue: 2000, month: 4 } 
]

Query Reference:
-------------------
printjson() : JS library function to display the JSON Object data.
    In db.<collection>.find()/aggregate():
    	db -> Refers to the database.
    	<collection> -> Your collection name
	
*/
	
printjson(
    db.billing.aggregate([
        {
            $addFields: {
                billingDateObj: {
                    $toDate: "$billingDate"
                }
            }  
        },
        {
            $group: {
                _id: {$month: "$billingDateObj"},
                totalRevenue: {$sum: "$totalAmount"}
            }
        },
        {
            $project: {
                _id: 0,
                totalRevenue: 1,
                month: "$_id"
            }
        }
    ])
)
